# Generated by Django 3.1.7 on 2021-03-21 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('courier_type', models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=4)),
                ('regions', models.JSONField(blank=True, default=list, null=True)),
                ('working_hours', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('region', models.IntegerField()),
                ('delivery_hours', models.JSONField(blank=True, default=list, null=True)),
                ('assign_time', models.DateTimeField(blank=True, null=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('courier_type', models.CharField(blank=True, choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=4, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.courier')),
            ],
        ),
    ]
