# Generated by Django 3.1.7 on 2021-03-20 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assign_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.courier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier_type',
            field=models.CharField(blank=True, choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=4, null=True),
        ),
    ]
